Import all relevant functions.

In [192]:
import pandas as pd
import pandasql as ps 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from joblib import dump, load

Store the cleaned dataset into a variable.

In [193]:
dataset_path = "data_new.csv"
dataset = pd.read_csv(dataset_path)

dataset

,clicks,median_click_interval_ms,click_interval_std_ms,mouse_path_curvature,mouse_distance_px,idle_ratio,scroll_entropy,digraph_latency_ms,dwell_field1_ms,dwell_field2_ms,dwell_field3_ms,session_duration_ms,pages_visited,timezone_mismatch,button_hover_ms,copy_events,viewport_width,webdriver_flag,bot
0,31,201,78,0.766,710,0.378,1.32,124,733,984,345,7987,7,0,0,1,414,0,0
1,23,832,40,0.297,983,0.360,1.13,168,331,327,326,24925,4,0,0,1,375,0,1
2,26,342,41,0.122,1750,0.932,2.20,91,666,652,649,18157,1,0,0,0,1366,1,1
3,27,619,269,0.312,2084,0.423,1.79,135,777,761,611,22211,1,0,0,0,1366,0,0
4,30,522,160,0.856,2106,0.204,1.22,169,1011,205,570,16304,5,0,0,1,1920,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,25,817,672,0.458,8070,0.274,1.00,148,362,899,501,22937,6,0,332,1,1366,0,0
317,23,394,243,0.905,3122,0.286,2.17,160,278,997,185,12774,3,0,343,4,1440,0,0
318,29,831,355,0.585,9846,0.411,3.04,134,838,560,936,35412,5,0,347,1,1366,0,0
319,34,350,217,0.467,8100,0.611,2.29,108,571,645,620,18029,8,0,354,1,1920,0,0
320,24,551,92,0.806,9263,0.650,1.30,98,651,531,909,21327,3,0,358,2,1440,0,0

Use one-hot encoding to convert all variables to numerical form.

In [194]:
dataset_encoded = pd.get_dummies(dataset)
dataset_encoded = dataset_encoded.astype(int)
dataset_encoded

,clicks,median_click_interval_ms,click_interval_std_ms,mouse_path_curvature,mouse_distance_px,idle_ratio,scroll_entropy,digraph_latency_ms,dwell_field1_ms,dwell_field2_ms,dwell_field3_ms,session_duration_ms,pages_visited,timezone_mismatch,button_hover_ms,copy_events,viewport_width,webdriver_flag,bot
0,31,201,78,0,710,0,1,124,733,984,345,7987,7,0,0,1,414,0,0
1,23,832,40,0,983,0,1,168,331,327,326,24925,4,0,0,1,375,0,1
2,26,342,41,0,1750,0,2,91,666,652,649,18157,1,0,0,0,1366,1,1
3,27,619,269,0,2084,0,1,135,777,761,611,22211,1,0,0,0,1366,0,0
4,30,522,160,0,2106,0,1,169,1011,205,570,16304,5,0,0,1,1920,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,25,817,672,0,8070,0,1,148,362,899,501,22937,6,0,332,1,1366,0,0
317,23,394,243,0,3122,0,2,160,278,997,185,12774,3,0,343,4,1440,0,0
318,29,831,355,0,9846,0,3,134,838,560,936,35412,5,0,347,1,1366,0,0
319,34,350,217,0,8100,0,2,108,571,645,620,18029,8,0,354,1,1920,0,0
320,24,551,92,0,9263,0,1,98,651,531,909,21327,3,0,358,2,1440,0,0

Seperate the bot column from the rest of the columns.

In [195]:
y = dataset_encoded["bot"]
X = dataset_encoded.drop(["bot"], axis=1)

In [196]:
X

,clicks,median_click_interval_ms,click_interval_std_ms,mouse_path_curvature,mouse_distance_px,idle_ratio,scroll_entropy,digraph_latency_ms,dwell_field1_ms,dwell_field2_ms,dwell_field3_ms,session_duration_ms,pages_visited,timezone_mismatch,button_hover_ms,copy_events,viewport_width,webdriver_flag
0,31,201,78,0,710,0,1,124,733,984,345,7987,7,0,0,1,414,0
1,23,832,40,0,983,0,1,168,331,327,326,24925,4,0,0,1,375,0
2,26,342,41,0,1750,0,2,91,666,652,649,18157,1,0,0,0,1366,1
3,27,619,269,0,2084,0,1,135,777,761,611,22211,1,0,0,0,1366,0
4,30,522,160,0,2106,0,1,169,1011,205,570,16304,5,0,0,1,1920,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,25,817,672,0,8070,0,1,148,362,899,501,22937,6,0,332,1,1366,0
317,23,394,243,0,3122,0,2,160,278,997,185,12774,3,0,343,4,1440,0
318,29,831,355,0,9846,0,3,134,838,560,936,35412,5,0,347,1,1366,0
319,34,350,217,0,8100,0,2,108,571,645,620,18029,8,0,354,1,1920,0
320,24,551,92,0,9263,0,1,98,651,531,909,21327,3,0,358,2,1440,0

In [197]:
y

0      0
1      1
2      1
3      0
4      0
      ..
316    0
317    0
318    0
319    0
320    0
Name: bot, Length: 321, dtype: int64

Split X and y into training and testing datasets.

In [198]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [199]:
X_train

,clicks,median_click_interval_ms,click_interval_std_ms,mouse_path_curvature,mouse_distance_px,idle_ratio,scroll_entropy,digraph_latency_ms,dwell_field1_ms,dwell_field2_ms,dwell_field3_ms,session_duration_ms,pages_visited,timezone_mismatch,button_hover_ms,copy_events,viewport_width,webdriver_flag
180,32,659,44,0,975,0,1,79,689,702,698,32892,4,0,101,3,1920,0
17,29,203,8,0,8277,0,0,139,460,463,460,10861,5,0,0,2,1366,0
24,34,580,62,0,15334,0,2,30,232,233,230,32550,6,0,0,1,414,0
176,29,586,27,0,12398,0,1,191,597,587,596,24443,7,0,99,2,1366,0
110,21,687,60,0,7624,0,1,9,752,747,742,16554,4,0,59,1,1920,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,25,703,163,0,54091,0,1,176,809,340,904,25068,6,1,109,3,1440,0
71,30,777,755,0,1851,0,2,124,815,0,251,39649,6,0,37,2,414,0
106,23,596,16,0,10977,0,1,68,779,774,770,20272,4,0,56,1,375,0
270,35,771,536,0,46347,0,2,171,1115,527,801,44768,3,0,200,1,1440,0
102,38,749,379,0,6738,0,1,93,375,864,594,49965,13,0,55,1,375,0

In [200]:
X_test

,clicks,median_click_interval_ms,click_interval_std_ms,mouse_path_curvature,mouse_distance_px,idle_ratio,scroll_entropy,digraph_latency_ms,dwell_field1_ms,dwell_field2_ms,dwell_field3_ms,session_duration_ms,pages_visited,timezone_mismatch,button_hover_ms,copy_events,viewport_width,webdriver_flag
173,27,817,441,0,42604,0,1,111,494,446,194,31191,4,1,97,3,1440,0
132,21,641,183,0,14002,0,1,181,173,0,629,16485,7,0,74,0,1920,1
197,23,617,33,0,13001,0,2,44,534,543,538,20338,5,0,119,1,1366,0
9,27,261,15,0,3869,0,2,83,562,564,557,13364,5,0,0,1,375,1
104,24,571,41,0,4754,0,2,64,809,794,799,21933,4,0,56,2,375,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,31,538,13,0,28345,0,0,68,294,292,296,26665,5,0,155,3,414,0
60,23,560,540,0,12269,0,1,141,758,615,458,20679,5,0,29,2,414,0
289,25,536,493,0,2559,0,0,128,932,884,33,16395,7,0,233,1,1366,0
260,35,661,518,0,2284,0,2,80,548,1100,508,43002,8,0,185,0,375,0
118,32,804,583,0,9644,0,1,193,800,1006,984,43226,6,0,66,0,414,0

In [201]:
y_train

180    1
17     1
24     1
176    1
110    1
      ..
188    0
71     0
106    1
270    0
102    0
Name: bot, Length: 256, dtype: int64

In [202]:
y_test

173    0
132    0
197    1
9      1
104    1
      ..
229    1
60     0
289    0
260    0
118    0
Name: bot, Length: 65, dtype: int64

Scale the features on training data and apply it to both datasets.

In [203]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

Train with the classifier using the KNN with the highest accuracy.

In [204]:
acc_array = []
acc_highest = 0
acc_neighbour = 0

for i in range(len(y_train)):
    knn_class = KNeighborsClassifier(n_neighbors=i+1)
    knn_class.fit(X_train_scaled, y_train)
    
    y_pred = knn_class.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)

    acc_array.append(accuracy)

for i in range(len(acc_array)):
    if acc_array[i] > acc_highest:
        acc_highest = acc_array[i]
        acc_neighbour = i+1

knn_class = KNeighborsClassifier(n_neighbors=acc_neighbour)
knn_class.fit(X_train_scaled, y_train)

KNeighborsClassifier()

Test out the accuracy of the classifier along with the KNN value used.

In [205]:
y_pred = knn_class.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred) 
print(f"Accuracy : {accuracy:.4f}")
print(f"KNN Value : {acc_neighbour}")

Accuracy : 0.9692
KNN Value : 5

In [206]:
acc_array = []
acc_highest = 0
acc_neighbour = 0

for i in range(len(y_train)):
    knn_class = KNeighborsClassifier(n_neighbors=i+1)
    knn_class.fit(X_train_scaled, y_train)
    
    y_pred = knn_class.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)

    acc_array.append(accuracy)

for i in range(len(acc_array)):
    if acc_array[i] > acc_highest:
        acc_highest = acc_array[i]
        acc_neighbour = i+1

knn_class = KNeighborsClassifier(n_neighbors=acc_neighbour)
knn_class.fit(X_train_scaled, y_train)
    
y_pred = knn_class.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred) 
print(accuracy)
print(acc_neighbour)

0.9692307692307692
5

Checks if accuracy improves if a feature is removed and outputs the features that improve or worsen accuracy when removed.

In [207]:
worse_removed = []
better_removed = []
remove = []

for i in range(len(dataset.columns)-1):
    tdataset = dataset.drop(dataset.columns[i], axis=1)
    tdataset_encoded = pd.get_dummies(tdataset)

    ty = tdataset_encoded["bot"]
    tX = tdataset_encoded.drop(["bot"], axis=1)

    tX_train, tX_test, ty_train, ty_test = train_test_split(tX, ty, test_size=0.2, random_state=42)

    tscaler = StandardScaler()
    tscaler.fit(tX_train)

    tX_train_scaled = tscaler.transform(tX_train)
    tX_test_scaled = tscaler.transform(tX_test)

    tknn_class = KNeighborsClassifier(n_neighbors=18)
    tknn_class.fit(tX_train_scaled, ty_train)

    ty_pred = tknn_class.predict(tX_test_scaled)

    if accuracy_score(ty_test, ty_pred) <= 0.9692307692307692:
        worse_removed.append(dataset.columns[i])
    else:
        better_removed.append(dataset.columns[i])
        remove.append(i)

print(worse_removed)
print(better_removed)

['clicks', 'median_click_interval_ms', 'click_interval_std_ms', 'mouse_path_curvature', 'mouse_distance_px', 'idle_ratio', 'scroll_entropy', 'digraph_latency_ms', 'dwell_field1_ms', 'dwell_field2_ms', 'dwell_field3_ms', 'session_duration_ms', 'pages_visited', 'timezone_mismatch', 'button_hover_ms', 'copy_events', 'viewport_width', 'webdriver_flag']
[]

In [209]:
dump(knn_class, "bvh_knn_model48.joblib")
dump(scaler, "bvh_scaler48.joblib")

['bvh_scaler48.joblib']